### ISSUE TITLE
CTD when changing the ES active runway selection

### ISSUE THREAD

**Issue by kusterjs** [LB767/vSMR#23]
When an instance of a vSMR radar has been opened and the active runway are changed via the ES dialog, ES (r25) crashes to desktop.

**Comment by LB767** [comment]
I'm gonna need more details of what you did when this happened if you still remember because I can't reproduce it on my side after a quick test...

**Comment by kusterjs** [comment]
It happens with when the ES has been running for some time, when there is a decent number of traffic and you change active runways. Upon the klick to confirm these runway settings. It takes a while with ES to set the active sectors accordingly again and switch the runway extended centrelines drawing. But when ES crashes without prior notice or any error message.
Is there any kind of log (of vSMR or ES) which I could use to get more information? I haven't found one yet.

**Comment by LB767** [comment]
I'll try and have a look again this weekend... were you on Swiss Radar? Did you have multiple airports selected in the runway settings or just one?

**Comment by kusterjs** [comment]
Yes it was on Swiss Radar with multiple airports active, and multiple runways of course as well. Did change the runway settings of one airport only though. But I think this doesn't really matter.

**Comment by LB767** [comment]
If your crash was an OOM, it should be fixed with the new release... hopefully

**Comment by kusterjs** [comment]
Unfortunately, this issue is still present and can be reproduced easily when a lot of traffic is around and ES has been running for a while. The Tuesday evening runway change is a typical situation where the crash can be expected. The only way to prevent it is to not open any instance of vSMR before the runway change. It doesn't help if you had opened an instance and close it before. So it seems there is still something running from vSMR and the deconstructor is not complete.
Attached is one of my dump logs. Maybe it can help you to identify the issue?
[EuroScope_crash_.zip](https://github.com/LB767/vSMR/files/5855762/EuroScope_crash_.zip)

**Comment by LB767** [comment]
I have yet to ever experience this crash... which is really annoying.
If you have time at some point can you try and see if you can make it crash when playing a scenario file instead of live?

**Comment by LB767** [comment]
Also considering I can't seem to get the crash myself, if you're REALLY motivated and since you're more familiar with plugins you could also download the Visual Studio project and run it in debug mode during a controlling session, then when it crashes we can know exactly where it happens. Happy to help you get the project files working if you want to, just let me know.

**Comment by kusterjs** [comment]
Did a test yesterday with a playback log file, unfortunately I couldn't reproduce.
